export enum ActivityLogActionType {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  APPROVAL = 'APPROVAL',
  VERIFY = 'VERIFY',
  LINK = 'LINK',
  UNLINK = 'UNLINK',
  ASSIGN = 'ASSIGN',
  REQUEST = 'REQUEST',
  SUBMIT = 'SUBMIT',
  AUTHENTICATE = 'AUTHENTICATE',
}

export enum ActivityLogResourceType {
  USER = 'USER',
  PROJECT = 'PROJECT',
  NOTIFICATION = 'NOTIFICATION',
  OAUTH_METADATA = 'OAUTH_METADATA',
  ID_CARD = 'ID_CARD',
  TIME_LOG = 'TIME_LOG',
  TASK_ASSIGNMENT = 'TASK_ASSIGNMENT',
  PRICE_FORM = 'PRICE_FORM',
  CLIENT = 'CLIENT',
  WORKER = 'WORKER',
  DESIGNER = 'DESIGNER',
  SUPPLIER = 'SUPPLIER',
  VENDOR = 'VENDOR',
  USER_TYPE = 'USER_TYPE',
  ROLE = 'ROLE',
  PERMISSION = 'PERMISSION',
  LOGIN_SESSION = 'LOGIN_SESSION',
  LOGIN_ATTEMPT = 'LOGIN_ATTEMPT',
  ADDRESS = 'ADDRESS',
  CONTACT = 'CONTACT',
  PROJECT_SPACE_DETAILS = 'PROJECT_SPACE_DETAILS',
  VENDOR_ORDER = 'VENDOR_ORDER',
  VENDOR_ORDER_ITEMS = 'VENDOR_ORDER_ITEMS',
  VENDOR_CATEGORY = 'VENDOR_CATEGORY',
  USER_ROLE = 'USER_ROLE',
  ROLE_PERMISSION = 'ROLE_PERMISSION',
  GENERAL = 'GENERAL',
}

export enum ActivityLogErrorCode {
  CAPTURE_FAILED = 'ACTIVITY_LOG_CAPTURE_FAILED',
  INVALID_DATA = 'ACTIVITY_LOG_INVALID_DATA',
  DATABASE_ERROR = 'ACTIVITY_LOG_DATABASE_ERROR',
}

export const ActivityLogMessage = {
  CAPTURED: 'Activity logged successfully',
  CAPTURE_FAILED: 'Failed to capture activity log',
  INVALID_DATA: 'Invalid activity log data',
  DATABASE_ERROR: 'Database error while logging activity',
} as const;
